### ISSUE TITLE
TimedOutError handling

### ISSUE THREAD

**Issue by idlesign** [hamano/pysmbc#10]
Hi,

Just faced `TimedOutError`. Tried to pass `timeout` into `Context.__init__`, but it won't accept it. Tried to supply `.timeout` attribute to context object, but it seemed to have no effect.

Is there any way I can increase the default timeout?

**Comment by hamano** [comment]
Did you try Context_setTimeout()?
I remember it worked.

**Comment by idlesign** [comment]
No, but I will and inform you if any luck. Thank you.

**Comment by idlesign** [comment]
From what I see (https://github.com/hamano/pysmbc/blob/master/smbc/context.c#L972) `Context_setTimeout()` is wired exactly into `Context.timeout`. So it should have been worked. I'll recheck.

**Comment by idlesign** [comment]
For history. The following should work:
```
smb = smbc.Context(auth_fn=auth)
smb.timeout = 1000  # ms
```
