### ISSUE TITLE
getxattr returns incomplete security descriptor strings

### ISSUE THREAD

**Issue by debjit-bhattacharjee** [hamano/pysmbc#11]
Since Context_getxattr uses a 1024 byte sized array to store the security descriptor string, anything longer than that gets truncated.

**Comment by hamano** [comment]
Hi, thanks for your contribute!
We might as well use stack memory:
char value[375315];

**Comment by debjit-bhattacharjee** [comment]
Sure. I have updated the pull request to use stack memory instead of heap.
