### ISSUE TITLE
ctx = smbc.Context(auth_fn=my_auth_callback_fn)

### ISSUE THREAD

**Issue by barrachri** [hamano/pysmbc#14]
Hello, do you think is possible to have more info about how to use the `my_auth_callback_fn`?

Am I right that the function should return the values as below?
```
def auth_fn(server, share, workgroup, username, password):
    return (workgroup, settings.USERNAME, settings.PASSWORD)
```

**Comment by hamano** [comment]
Yes, you can use it by that way.
we also suppose a GUI interface so It's a callback.
