### ISSUE TITLE
Adding wheels (binary) release to pysmbc

### ISSUE THREAD

**Issue by zehome** [hamano/pysmbc#20]
My last patch added support for setuptools, which enables the possibility to generate wheels (binary) of pysmbc.

The release is hosted here: https://github.com/zehome/pysmbc-wheels

Wheels are generated against manylinux1, so it should work on most post centos-5 linux systems.

Do you want to take over the wheels package and upload it yourself to pypi or should I handle it?

**Comment by zehome** [comment]
You can see the resulting wheels here: https://github.com/zehome/pysmbc-wheels/releases

**Comment by hamano** [comment]
Hi, The libsmbclient API has been changed frequently.
So I can not release pysmbc binaries that run on any linux distribution.

**Comment by zehome** [comment]
yes you can, check out my repository, libsmbclient is embedded inside the wheel

**Comment by zehome** [comment]
built against manylinux1 so you can use it on any GLIBC >= manylinux1.

**Comment by hamano** [comment]
Static linking is good idea for practical use. but I can't support it.
If we distribute it, we must take on the responsibilities that to maint libsmbclient binary.
Specifically, if vulnerability found inside libsmbclient, we have to fix our distribution.
So, I don't release binary.
Thanks.
