### ISSUE TITLE
Fix Some Holes In Error Checking And Potential Memory Leaks

### ISSUE THREAD

**Issue by ldo** [hamano/pysmbc#33]
The following patch [ldo-structured-error-checks.patch.txt](https://github.com/hamano/pysmbc/files/3684451/ldo-structured-error-checks.patch.txt) reworks some routines to fix holes in error checking and potential memory leaks from error recovery.

The basic principle is, all temporary object pointers are initialized to `NULL` at the start, and unconditionally passed to `Py_XDECREF` at end. Ownership of objects being constructed is only passed from temporary to result pointers after completion of all operations without errors. Note in particular how the loop-within-a-loop is handled in the `Dir.getdents()` routine.

**Comment by hamano** [comment]
could you make pull requests?

**Comment by ldo** [comment]
Thank you for accepting this. Closing.
