### ISSUE TITLE
no new release

### ISSUE THREAD

**Issue by 0xFF1E071F** [hamano/pysmbc#42]
Hello,
I can download the latest release from PyPi but i cannot from Github. Can you plaese provide the latest release?
Thank you =)

**Comment by hamano** [comment]
now 1.0.20 released.
Thanks

**Comment by 0xFF1E071F** [comment]
Thank you =)

**Comment by hamano** [comment]
now tagged 1.0.20.
I often forget tagging. sorry.

**Comment by 0xFF1E071F** [comment]
Thank you very much =)
