### ISSUE TITLE
pip install fails to install v1.0.22

### ISSUE THREAD

**Issue by mrakitin** [hamano/pysmbc#53]
Hello, I am trying to package the newest version 1.0.22 via https://github.com/nsls-ii-forge/pysmbc-feedstock/pull/3, but am observing a strange error:
```py
Processing $SRC_DIR
  Created temporary directory: /tmp/pip-req-build-s006bzfn
  Added file://$SRC_DIR to build tracker '/tmp/pip-req-tracker-i5g6rske'
    Running command python setup.py egg_info
    Running setup.py (path:/tmp/pip-req-build-s006bzfn/setup.py) egg_info for package from file://$SRC_DIR
    Created temporary directory: /tmp/pip-pip-egg-info-k6_ulgzy
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-s006bzfn/setup.py", line 117, in <module>
        define_macros=pkgconfig_Dversion("smbclient"),
      File "/tmp/pip-req-build-s006bzfn/setup.py", line 82, in pkgconfig_Dversion
        ver = str(int(vers[0]) * 10000 + int(vers[1]) * 100 + int(vers[2]))
    IndexError: list index out of rang
```
Have you observed it? Is there any known workaround? I am using `python -m pip install . --no-deps -vv` command during conda build. Thanks!

**Comment by hamano** [comment]
`pkgconfig_Dversion("smbclient")` will jsut call `pkg-config --modversion smbclient`
Probably, your environment has not pkg-config or libsmbclient.

**Comment by mrakitin** [comment]
Thanks for the reply! The `pkg-config` and `libsmbclient` are installed. I used a CentOS-based Docker image for my tests. Steps to reproduce:
```bash
(host) $ docker run -it --rm -v $PWD:/build:rw,z condaforge/linux-anvil-comp7 bash
$ sudo yum install -y samba samba-client libsmbclient-devel
...
$ pkg-config --modversion smbclient
0
$ cat /usr/lib64/pkgconfig/smbclient.pc
prefix=/usr
exec_prefix=/usr
libdir=/usr/lib64
includedir=/usr/include

Name: Samba libsmbclient
Description: A library to access CIFS servers
Version: 0
URL: http://www.samba.org/
#Libs: -L/usr/lib64 -lsmbclient
Libs: -lsmbclient
Libs.private: -lsmbclient  -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -lldap -llber  -lcap -lresolv -lnsl -ldl -lrt -lrt
Cflags: -I/usr/include

```

This is how the `/usr/lib64/pkgconfig/smbclient.pc` file looks like:
```
prefix=/usr
exec_prefix=/usr
libdir=/usr/lib64
includedir=/usr/include

Name: Samba libsmbclient
Description: A library to access CIFS servers
Version: 0
URL: http://www.samba.org/
#Libs: -L/usr/lib64 -lsmbclient
Libs: -lsmbclient
Libs.private: -lsmbclient  -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -lldap -llber  -lcap -lresolv -lnsl -ldl -lrt -lrt
Cflags: -I/usr/include
```
I tried to run the same on a Debian 8-based image, but it did not even have any files in `/usr/lib/pkgconfig`.

It does not look like the `pkg-config --modversion smbclient` way to extract the client's version is robust enough. I guess this line in the function 
https://github.com/hamano/pysmbc/blob/43bce81a8cbe269a6bd90582d25a875e2f1c8202/setup.py#L82
should fall back to parsing the output of `smbclient -V`:
```bash
# in CentOS:
$ smbclient -V
Version 3.6.23-53.el6_10

# in Debian:
$ smbclient -V
Version 3.6.6
```

**Comment by mrakitin** [comment]
@hamano, please see this full build log for details: https://dev.azure.com/nsls2forge/nsls2forge/_build/results?buildId=4311&view=logs&j=517fe804-fa30-5dc2-1413-330699242c05&t=c10fa5f2-fdf6-5338-3bdb-c4bea7c23412. It fails on parsing of that version `0`.

**Comment by mrakitin** [comment]
I proposed a fix via #54.

**Comment by hamano** [comment]
I checked smbclient.pc on CentOS. it seems listed version tag corectly.
Just now I fixed it with wrong smbclient.pc.
You can't get the correct version, but it's not a big issue.
There is a workaround if you want to get the correct version.

~~~
$ mkdir ./pkgconfig
$ cp /usr/lib64/pkgconfig/smbclient.pc ./pkgconfig
$ vim  ./pkgconfig/smbclient.pc # fix Version tag properly
$ PKG_CONFIG_PATH=./pkgconfig pkg-config --modversion smbclient
or
$ PKG_CONFIG_PATH=./pkgconfig pip ...
~~~

**Comment by mrakitin** [comment]
Thank you. I saw the fix in https://github.com/hamano/pysmbc/commit/3cc7947134c0f82b67a42684fb63ec203498f481.
