### ISSUE TITLE
Rework Context.getxattr() To Only Allocate Needed Buffer Space

### ISSUE THREAD

**Issue by ldo** [hamano/pysmbc#56]
The following patch [ldo-getxattr.patch.txt](https://github.com/hamano/pysmbc/files/5360482/ldo-getxattr.patch.txt) reworks the `Context.getxattr()` routine to only allocate the needed space for the actual attributes that will be returned, rather than assuming some kind of fixed worst-case size.

**Comment by hamano** [comment]
applied thanks

**Comment by hamano** [comment]
@ldo
It seems your patch broke tests/test_context.py:test_xattr_get()
could you check it?
(ps: I'm rewriting nosetest into pytest)

**Comment by ldo** [comment]
Yeah, looks like the buffer size needs to be one bigger. This extra patch 
[ldo-getxattr-bufsize.patch.txt](https://github.com/hamano/pysmbc/files/5405754/ldo-getxattr-bufsize.patch.txt) gets that test to pass now.

**Comment by hamano** [comment]
thanks
