### ISSUE TITLE
setxattr() input and getxattr() output doesn't match

### ISSUE THREAD

**Issue by parthsompura** [hamano/pysmbc#61]
Hello Team,

We are trying to update the permissions of a folder using `pysmbc` module where we first try to set the permissions using `setxattr()` and then retrieve using the `getxattr()` to verify that the permissions have been updated correctly but we get all permissions revoked after applying `setxattr()`.

Trying to set the following data and received success (`0`) response:

`REVISION:1,OWNER:S-1-5-21-1307774611-3696762510-3468689618-1000,GROUP:S-1-5-21-1307774611-3696762510-3468689618-513,ACL:S-1-1-0:0/0/0x001f01ff,ACL:S-1-5-21-1307774611-3696762510-3468689618-1000:0/16/0x001f01ff,ACL:S-1-5-32-544:0/16/0x001f01ff,ACL:S-1-5-18:0/16/0x001f01ff,ACL:S-1-1-0:0/16/0x001f01ff`

While fetching we get the following data:

`REVISION:1,OWNER:S-1-5-21-1307774611-3696762510-3468689618-1000,GROUP:S-1-5-21-1307774611-3696762510-3468689618-513,ACL:S-1-1-0:0/0/0x00000000,ACL:S-1-1-0:0/16/0x00000000,ACL:S-1-5-18:0/16/0x00000000,ACL:S-1-5-32-544:0/16/0x00000000,ACL:S-1-5-21-1307774611-3696762510-3468689618-1000:0/16/0x00000000`

Correspondingly the actual access is getting revoked in the WFS!

PS: Just to confirm that we are using `pysmbc-1.0.23` version and wondering if this has been already fixed in some other versions. Kindly update ASAP.

**Comment by mkhandhar** [comment]
Hello Team, request you to kindly check this issue and respond as quickly as possible.

**Comment by hamano** [comment]
@mkhandhar @parthsompura 
Do you think it's libsmbclient side issue or binding issue?
I wellcome your PR.

**Comment by parthsompura** [comment]
@hamano we are not sure what's the exact issue but it seems that binding is just transfer of the input data while `libsmbclient` has the actual logic.

Also we tried to debug the `context.c` but it has so many unresolved references so could not able to run/debug it.  Along with that we tried to execute the linux command `smbcacls` and we were able to change the permissions properly. 

Is it possible to have a call so that we can explain the issue properly?
I welcome your prompt response.

**Comment by mkhandhar** [comment]
Based on the above comment from @anagda3  this issue us resolved

**Comment by parthsompura** [comment]
Based on our findings we are doing some change and raising one PR where we are updating the `setxattr()` specific test cases which was skipped previously so that it can help others, but we are getting the following error:

```
remote: Permission to hamano/pysmbc.git denied to parthsompura.
fatal: unable to access 'https://github.com/hamano/pysmbc.git/': The requested URL returned error: 403
```

@hamano kindly grant us the access to raise the PR

**Comment by mkhandhar** [comment]
@hamano  kindly reply for the above request.
