### ISSUE TITLE
Windows SACL File Audit Policy lists 

### ISSUE THREAD

**Issue by Nocturem** [hamano/pysmbc#8]
Hi there,

with 
Context = smbc.Context()
ACL = Context.getxattr("smb://UserName:Password@SharePath", smbc.XATTR_ALL)
I am able to obtain the revision owner group and Discrete ACL 

Is there any support for the System Access Control List 

Cheers 
Pearce

**Comment by hamano** [comment]
Ya, pysmbc supports getxattr() and setxattr()
see tests/test_context.py.
Thank you.
